#ifndef SENTINEL_EVENT_H
#define SENTINEL_EVENT_H

typedef enum {
	SENTINEL_EVENT_INVALID = 0,
	SENTINEL_EVENT_STARTUP_COMPLETE,
	SENTINEL_EVENT_HEARTBEAT_WARNING,
	SENTINEL_EVENT_COMMUNICATION_LOST,
	SENTINEL_EVENT_INCOHERENT_PEER_STATE,
	SENTINEL_EVENT_FAULT_CLEARED,
	SENTINEL_EVENT_FAULT_ESCALATED,
	SENTINEL_EVENT_MANUAL_RESET
} SentinelEvent;

const char *sentinel_event_to_string(SentinelEvent event);

#endif // !SENTINEL_EVENT_H
