#ifndef SENTINEL_EVENT_H
#define SENTINEL_EVENT_H

typedef enum {
	SENTINEL_EVENT_INVALID = 0,
	SENTINEL_EVENT_COMM_LOST,
	SENTINEL_EVENT_COMM_OK,
	SENTINEL_EVENT_FAULT_ESCALATED,
	SENTINEL_EVENT_HEARTBEAT_OK,
	SENTINEL_EVENT_HEARTBEAT_TIMEOUT,
	SENTINEL_EVENT_RESET_REQUESTED,
	SENTINEL_EVENT_SYSTEM_START,
	SENTINEL_EVENT_VALUE_INCONSISTENT,
	SENTINEL_EVENT_VALUE_OK,
} SentinelEvent;

const char *sentinel_event_to_string(SentinelEvent event);

#endif // !SENTINEL_EVENT_H
